### ISSUE TITLE
Question about details / theory

### ISSUE THREAD

**Issue by JoOkuma** [maurosilber/SMO#1]
Hi Mauro, awesome package.

Do you have any material/reference about the Silver Mountain Operator?

Thanks

**Comment by maurosilber** [comment]
Hi, thank you! :smile:

Yes, sure! We recently posted a [pre-print on biorxiv](https://www.biorxiv.org/content/10.1101/2021.11.09.467975v1). We tweeted about it [here](https://twitter.com/maurosilber/status/1459174835662344200), but I guess you found this package in some other way. I'll add it to the README.

**Comment by JoOkuma** [comment]
Thanks again :)
